#!/bin/bash
# Regenerates research/INDEX.md from frontmatter in research/*.md files.
# Usage: ./scripts/build-index.sh  (run from repo root)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RESEARCH_DIR="$REPO_ROOT/research"
INDEX_FILE="$RESEARCH_DIR/INDEX.md"

extract_frontmatter_field() {
  local file="$1"
  local field="$2"
  awk -v field="$field" '
    BEGIN { in_fm = 0 }
    NR == 1 && /^---[[:space:]]*$/ { in_fm = 1; next }
    in_fm && /^---[[:space:]]*$/ { exit }
    in_fm {
      if ($0 ~ "^" field ":") {
        sub("^" field ":[[:space:]]*", "")
        gsub(/^"|"$/, "")
        print
        exit
      }
    }
  ' "$file"
}

extract_first_heading() {
  awk '/^# / { sub(/^# /, ""); print; exit }' "$1"
}

extract_last_updated() {
  awk '
    /\*Last updated:/ {
      match($0, /[A-Z][a-z]+ [0-9]+,? [0-9]{4}/)
      if (RSTART > 0) {
        print substr($0, RSTART, RLENGTH)
        exit
      }
    }
  ' "$1"
}

file_age_days() {
  local file="$1"
  local mtime
  mtime=$(stat -f %m "$file" 2>/dev/null || stat -c %Y "$file" 2>/dev/null)
  local now
  now=$(date +%s)
  echo $(( (now - mtime) / 86400 ))
}

{
  echo "# Research Index"
  echo ""
  echo "_Auto-generated by \`scripts/build-index.sh\`. Do not edit by hand — run the script to regenerate._"
  echo ""
  echo "_Last regenerated: $(date '+%Y-%m-%d %H:%M')_"
  echo ""
  echo "| Topic | File | Chain | Verified | Tags | Age |"
  echo "|---|---|---|---|---|---|"

  cd "$RESEARCH_DIR"
  for f in *.md; do
    if [[ "$f" == "INDEX.md" ]]; then continue; fi
    if [[ ! -f "$f" ]]; then continue; fi

    title=$(extract_frontmatter_field "$f" "title" || true)
    [[ -z "$title" ]] && title=$(extract_first_heading "$f")
    [[ -z "$title" ]] && title="$f"

    topic=$(extract_frontmatter_field "$f" "topic" || true)
    [[ -z "$topic" ]] && topic="—"

    chain=$(extract_frontmatter_field "$f" "chain" || true)
    [[ -z "$chain" ]] && chain="—"

    verified=$(extract_frontmatter_field "$f" "verified" || true)
    [[ -z "$verified" ]] && verified=$(extract_last_updated "$f")
    [[ -z "$verified" ]] && verified="(not specified)"

    tags=$(extract_frontmatter_field "$f" "tags" || true)
    [[ -z "$tags" ]] && tags="—"

    age_days=$(file_age_days "$f")
    if (( age_days > 30 )); then
      age="${age_days}d ⚠"
    else
      age="${age_days}d"
    fi

    echo "| $topic | [\`$f\`](./$f) | $chain | $verified | $tags | $age |"
  done

  echo ""
  echo "## Conventions"
  echo ""
  echo "Each research file should have YAML frontmatter at the top:"
  echo ""
  echo '```yaml'
  echo "---"
  echo "title: Human-readable title"
  echo "topic: Short category (e.g., BNB LST, XAUT, Lista DAO)"
  echo "chain: Blockchain (e.g., BSC, Ethereum)"
  echo "verified: YYYY-MM-DD"
  echo "tags: [tag1, tag2]"
  echo "---"
  echo '```'
  echo ""
  echo "Files with no frontmatter fall back to heading + \`*Last updated:*\` line."
  echo "The **Age** column flags files not modified in over 30 days — these may need re-verification."
} > "$INDEX_FILE"

echo "Regenerated $INDEX_FILE"
